version: "3"
services:
    postgres:
        image: "postgres:12.13-alpine3.17"
        container_name: "bd_arquitetura"
        # image: "postgres:13-alpine3.19"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=arqhex
        ports:
            - "5432:5432"
        # volumes:
        #     - /postgres-data:/var/lib/postgresql/data
